name: Deploy to FTP

on:
  push:
    branches: [ main ]  # Adjust if you use a different branch for production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (choose your node version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or use 18 if preferred

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build your project
      - name: Build project
        run: npm run build

      # Step 5: Deploy built files via FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: dist/    # Change if your build output folder has a different name
          server-dir: ${{ secrets.FTP_PATH }}  # This should be 'public_html'
